import './globals.css'
import Header from "@/components/header";
import Footer from "@/components/Footer"
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
<<<<<<< home-page
import Contact from '@/components/Contact';

=======
>>>>>>> main
config.autoAddCss = false

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
          <Header/>
          {children}
          <Contact/>
          <Footer/>
      </body>
    </html>
  )
}
